### ISSUE TITLE
Elements are duplicated on configurator input form

### ISSUE THREAD

**Issue by jml3310** [Upperstage/configurator#2]
Elements are duplicated on the Software Options section of the ACR-configurator web form.

![screenshot](https://user-images.githubusercontent.com/4580535/28022552-819ac490-6559-11e7-8afb-0aff50537c1c.png)

Using google-chrome 59.0.3071.115 on Linux with latest version of the configurator software.

**Comment by Upperstage** [comment]
I see same

**Comment by Upperstage** [comment]
Repaired duplicate options from displaying
